### ISSUE TITLE
instructions to obtain images 

### ISSUE THREAD

**Issue by sinatayebati** [luka-group/vlm-knowledge-conflict#2]
Hi @DarthZhu 

Thanks for the great work! I read through the code and documentation, but I couldn’t find where to download the actual images for either dataset. The JSON data released on both GitHub and Hugging Face only includes text and strings representing the images, but not the images themselves for input into the LLMs.

Could you please provide some information or instructions on how to obtain the images based on your cleaned partitions of the original datasets?

Thanks!

**Comment by DarthZhu** [comment]
Hi @sinatayebati,

Thanks for your interest in our work!

For the images, we are using the original images provided in the original datasets: [ViQuAE](https://huggingface.co/datasets/PaulLerner/viquae_dataset) and [InfoSeek](https://github.com/open-vision-language/infoseek). To access the images, please refer to the instructions in those original datasets.

Feel free to reach out if you have any further questions!

**Comment by sinatayebati** [comment]
@DarthZhu thanks for your reply. I was able to get the images of ViQae, but for InfoSeek I’m a bit confused as they don’t have clear documentation.

I’m using InfoSeek‘s HF dataset as the other method is deprecated. To this end, could you please confirm whether you extracted the files in [all_wikipedia_tar](https://huggingface.co/datasets/ychenNLP/oven/blob/main/all_wikipedia_images.tar)  or I should extract the ‘shard#.tar’ files? Also it appears they only released the test set, is this the same partition you used as well?

thanks in advance!

**Comment by DarthZhu** [comment]
@sinatayebati I just checked the InfoSeek repository, and it seems they've recently switched from Google Drive to HF.

For the partition, we are using the validation part of the InfoSeek as it provides gold answers. To download all the image files, you can refer to [here](https://github.com/edchengg/oven_eval/tree/main/image_downloads). Run all the bash files and then merge the images with `merge_oven_images.py`. This is the process I used to download the dataset, but I believe it's essentially the same as extracting all the `shard*` files in the HF repo.

I hope this helps with your issue. Let me know if you need further assistance!

**Comment by sinatayebati** [comment]
@DarthZhu Thanks for your response. Yes unfortunately they have changes their method with minimal documentation. I believe this should help figure this out for now. I will let you know if I have further questions. 

I close this issue. Thanks again for your support.

**Comment by sinatayebati** [comment]
resolved
